# config.yaml

# Hostname / IP
#
# Default: "0.0.0.0"
#
host: "0.0.0.0"

# Port
#
# Default: 42069
#
port: 42069

clients:
  # Client name used in the autobrr filter, can be customized to whatever you like
  # Note that a client name has to be unique and can only be used once
  #
  # Default: default
  #
  default:
    # qBittorrent Hostname / IP
    #
    # Default: "127.0.0.1"
    #
    host: "127.0.0.1"

    # qBittorrent Port
    #
    # Default: 8080
    #
    port: 8080

    # qBittorrent Username
    #
    # Default: "admin"
    #
    username: "admin"

    # qBittorrent Password
    #
    # Default: "adminadmin"
    #
    password: "adminadmin"

    # Pre Import Path of qBittorrent for Sonarr
    # Needs to be filled out correctly, e.g. "/data/torrents/tv-hd"
    #
    # Default: ""
    #
    preImportPath: ""

  # Below you can find an example on how to define a second qBittorrent client
  # If you want to define even more clients just copy this segment and adjust the values accordingly
  #
  #multi_client_example:
  #  host: "127.0.0.1"
  #
  #  port: 9090
  #
  #  username: "example"
  #
  #  password: "example"
  #
  #  preImportPath: ""

# seasonpackarr logs file
# If not defined, logs to stdout
# Make sure to use forward slashes and include the filename with extension. eg: "logs/seasonpackarr.log", "C:/seasonpackarr/logs/seasonpackarr.log"
#
# Optional
#
# logPath: ""

# Log level
# Default: "DEBUG"
#
# Options: "ERROR", "DEBUG", "INFO", "WARN", "TRACE"
#
logLevel: "DEBUG"

# Log Max Size
# Max log size in megabytes
#
# Default: 50
#
# logMaxSize: 50

# Log Max Backups
# Max amount of old log files
#
# Default: 3
#
# logMaxBackups: 3

# Smart Mode
# Toggles smart mode to only download season packs that have a certain amount of episodes from a release group
# already in the client
#
# Default: false
#
# smartMode: false

# Smart Mode Threshold
# Sets the threshold for the percentage of episodes out of a season that must be present in the client
# In this example 75% of the episodes in a season must be present in the client for it to be downloaded
#
# Default: 0.75
#
# smartModeThreshold: 0.75

# Parse Torrent File
# Toggles torrent file parsing to get the correct folder name
#
# Default: false
#
# parseTorrentFile: false

# API Token
# If not defined, removes api authentication
#
# Optional
#
# apiToken: ""