# config.toml

# Hostname / IP
#
# Default: "0.0.0.0"
#
host = "0.0.0.0"

# Port
#
# Default: 42069
#
port = 42069

# Pre Import Path of qBittorrent for Sonarr
# Needs to be filled out correctly, e.g. "/data/torrents/tv-hd"
#
# Default: ""
#
preImportPath = ""

# seasonpackarr logs file
# If not defined, logs to stdout
# Make sure to use forward slashes and include the filename with extension. eg: "logs/seasonpackarr.log", "C:/seasonpackarr/logs/seasonpackarr.log"
#
# Optional
#
#logPath = "logs/seasonpackarr.log"

# Log level
#
# Default: "DEBUG"
#
# Options: "ERROR", "DEBUG", "INFO", "WARN", "TRACE"
#
logLevel = "DEBUG"

# Log Max Size
#
# Default: 50
#
# Max log size in megabytes
#
#logMaxSize = 50

# Log Max Backups
#
# Default: 3
#
# Max amount of old log files
#
#logMaxBackups = 3