services:
  seasonpackarr:
    container_name: seasonpackarr
    image: ghcr.io/nuxencs/seasonpackarr
    restart: unless-stopped
    user: ${PUID}:${PGID} #UID and GID
    ports:
      - "127.0.0.1:42069:42069"
    environment:
      # Core settings
      SEASONPACKARR__DISABLE_CONFIG_FILE: false # set to true to not rely on config.yaml
      SEASONPACKARR__HOST: 0.0.0.0
      SEASONPACKARR__PORT: 42069
      SEASONPACKARR__API_TOKEN:

      # Logging settings
      SEASONPACKARR__LOG_LEVEL: DEBUG
      SEASONPACKARR__LOG_PATH:
      SEASONPACKARR__LOG_MAX_SIZE: 50
      SEASONPACKARR__LOG_MAX_BACKUPS: 3

      # Feature settings
      SEASONPACKARR__SMART_MODE: false
      SEASONPACKARR__SMART_MODE_THRESHOLD: 0.75
      SEASONPACKARR__PARSE_TORRENT_FILE: false

      # Fuzzy matching settings
      SEASONPACKARR__FUZZY_MATCHING_SKIP_REPACK_COMPARE: false
      SEASONPACKARR__FUZZY_MATCHING_SIMPLIFY_HDR_COMPARE: false

      # Notification settings
      SEASONPACKARR__NOTIFICATIONS_DISCORD:
      SEASONPACKARR__NOTIFICATIONS_NOTIFICATION_LEVEL: MATCH,ERROR

      # Client settings (can have multiple clients by changing DEFAULT to another name)
      SEASONPACKARR__CLIENTS_DEFAULT_HOST: 127.0.0.1
      SEASONPACKARR__CLIENTS_DEFAULT_PORT: 8080
      SEASONPACKARR__CLIENTS_DEFAULT_USERNAME: admin
      SEASONPACKARR__CLIENTS_DEFAULT_PASSWORD: adminadmin
      SEASONPACKARR__CLIENTS_DEFAULT_PREIMPORTPATH:
    volumes:
      - ${DOCKERCONFDIR}/seasonpackarr:/config # location of the config file
      - /data/torrents:/data/torrents # your torrent data directory
