FROM ubuntu:24.04

RUN apt-get update \
    && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends deluged=2.1.2~dev0+20240121-1 \
    && apt-get clean

COPY internal/torrentclient/testdata/deluge/entrypoint.sh /usr/local/bin/deluge-test-entrypoint

EXPOSE 58846
ENTRYPOINT ["/bin/sh", "/usr/local/bin/deluge-test-entrypoint"]
