FROM debian:buster-slim

RUN printf '%s\n' \
      'deb http://archive.debian.org/debian buster main' \
      'deb http://archive.debian.org/debian-security buster/updates main' \
      > /etc/apt/sources.list \
    && printf '%s\n' 'Acquire::Check-Valid-Until "false";' > /etc/apt/apt.conf.d/99archive \
    && apt-get update \
    && apt-get install -y --no-install-recommends deluged=1.3.15-2 \
    && apt-get clean

COPY internal/torrentclient/testdata/deluge/entrypoint.sh /usr/local/bin/deluge-test-entrypoint

EXPOSE 58846
ENTRYPOINT ["/bin/sh", "/usr/local/bin/deluge-test-entrypoint"]
